### ISSUE TITLE
basictracer requires child.Start() to be called before parent.Finish()

### ISSUE THREAD

**Issue by djspoons** [opentracing/basictracer-go#23]
e.g.
parent := StartSpan("p")
parent.Finish()
child := StartChildSpan(parent, "c") // <- panics

The semantic specification doesn't currently require StartChildSpan to be called before Finish. One use case is where the parent enqueues some future work and then calls Finish; the work is later removed from the queue and a child span is started.

On the other hand, perhaps this is not a true parent-child relationship...? The spec is not specific about what constitutes "parent-child and casual relationships." Perhaps intentionally? I'd argue that we should let the user define what 'parent-child' means.

**Comment by bg451** [comment]
@djspoons Given the code
```go
parent := StartSpan("p")
doAsyncStuff(parent)
parent.Finish()
```
doAsyncStuff starts a child span, but it may start after the parent span has finished, correct? The reason it then panics is because the parent gets cleared and put back into a pool, so you get nil references.

What about something like this? It's just a thought, since it seems like it would be a pain on the user's end.
```go
parent := StartSpan("p")
doAsyncStuff(StartChildSpan(parent, "queueing"), ...)
parent.Finish()

// And in doAsyncStuff
func doAsyncStuff(parent, ...) {
child := StartChildSpan(parent)
...
child.Finish()
parent.Finish()
}
```

I'll have to give this a bit of thought, but I just wanted to make sure that I'm understanding the case fully.

**Comment by jmacd** [comment]
How about something like this:

parent := StartSpan("p")
...
parentCtx := parent.Context()
...
parent.Finish()

child := startSpan(parentCtx, ...)
...

ᐧ

**Comment by bg451** [comment]
@jmacd The main issue I see with your proposal is that it would ask the user to use the basictracer package in areas besides the tracer init.

**Comment by djspoons** [comment]
@jmacd The problem (at least with the structure of the current basictracer implementation) is the Baggage, not the Context, but perhaps there's a way to make it work.

@bg451 I see what your doing, but we'd basically be asking the user to define a span solely for the purpose of copying the Baggage from "p" to "c".

**Comment by bg451** [comment]
@djspoons I suppose a quick way to get around this would be to add an option that disables the usage of the `spanImpl` pool. There'll be performance costs, but at least that way the span lives past the `Finish()` call.

**Comment by tschottdorf** [comment]
There's an extensive comment on the `Options` struct on this topic.

**Comment by jmacd** [comment]
@bg451 My proposal would require opentracing to incorporate some kind of
Context. This was mentioned in
https://github.com/opentracing/basictracer-go/pull/18 where I pointed out
that there would be good reasons for Context to outlive the Span.

@djspoons I'd say the distinction between Context and Baggage is artificial
and this is where it shows up. Or, conceptually, I'd say Baggage belongs in
Context.


ᐧ

**Comment by bg451** [comment]
@jmacd ah okay, I missed that. I figured your example meant introducing a method to the basictracer package.

**Comment by bg451** [comment]
Currently, the spec states that "Finish should be the last call made to any span instance, and to do otherwise leads to undefined behavior ([link](http://opentracing.io/spec/#the-span-interface))". I do think this applies to creating child spans, even if `StartChildSpan` doesn't specifically state that. With that in mind, I think that the use case counts as undefined behavior. 

That being said, I'd like to propose some rough ideas that don't touch the OpenTracing API (i.e. adding `Context()`)

1. Move `Baggage` into `Context` and add inject into/extract from Context. This kind of sucks though since you need the tracer handy in doAsyncStuff.
```go
parent := tracer.StartSpan("p")
traceCtx := Context{}
parent.Tracer().Inject(parent, CONTEXT, traceCtx) // Copies parent.raw.Context into traceCtx
doAsyncStuff(traceCtx, ...)
parent.Finish()
// . . .
func doAsyncStuff(...) {
  child, _  := tracer.Join("c", CONTEXT, traceCtx)
}
```
2. Same as above in terms of grabbing a copy of the `Context`, but use `net/context` as the carrier. 
3. Add an option to not use the `sync.pool` and therefore not recycle the `spanImpl`. (Personally not too big on this idea)

I'm a fan of option 2. @jmacd @djspoons thoughts?

**Comment by jmacd** [comment]
I like the idea of using the existing Inject / Join spec to accomplish this, and would agree it's best if a net/context.Context object is the carrier. Can't the net/context.Context object also carry a tracer reference? I'm still pretty new to OT, but I'm surprised we aren't talking about carrying active Span objects in a net/context.Context object as well.

**Comment by bg451** [comment]
So there is some stuff in the opentracing-go that uses net/context.Context https://github.com/opentracing/opentracing-go/blob/master/gocontext.go

**Comment by yurishkuro** [comment]
> @jmacd  Can't the net/context.Context object also carry a tracer reference?

it can, but I would leave that to the application, whereas using `net.Context` as an in-process Carrier would have to go into OT spec. The problem with the latter is that `net.Context` is actually immutable, so it's not possible to inject into it.

**Comment by yurishkuro** [comment]
the simplest way is to define a standard carrier
```go
type InMemoryCarrier struct {
    TracerContext interface{}
}
```

That struct can then be stored in `net.Context`. The whole thing can be wrapped into a helper method.

**Comment by bg451** [comment]
> `net.Context` is actually immutable

Huh, I never knew that, that's good to know. I'm taking it that doing something like passing a pointer to a context and doing `*ctx = context.WithValue(ctx, traceStateKey, parentSpan.Context())` isn't a good idea either.

I like the idea of an InMemoryCarrier. I feel like that shouldn't be part of the OT spec, just the opentracing-go package, since there is no expectation of interop between languages.

**Comment by yurishkuro** [comment]
It needs to be in opentracing-go, otherwise end-user code will not be portable. I don't mind having such standard format/carrier, + util functions to store it in the `net.Context`

**Comment by jmacd** [comment]
@yurishkuro I like your proposal. A standard / conventional set of utility functions to deal with net/context carriers, to promote interoperability.

When this sort of API is done and used properly, it can create really great traces of hierarchical operations with nested spans for child contexts, automatic logging of cancellation events. I haven't done this in Go before so I don't have more specific suggestions yet, but did some work on a similar API in C++.

**Comment by yurishkuro** [comment]
Ironically, this comes back full circle to the first OT implementations where a "trace context" was a first class citizen, and all marshaling and child creation was built around that Context, not the Span. The few actual OT implementations I know of are internally built with such context concept. We eventually removed that from public API because the way the end user would access it was virtually indistinguishable from operating on the Span directly. Which makes me wonder if we're going on the right path here trying to resurrect "trace context" in the form of the special carrier.

The primary use case here is `parentSpan.startChildSpan()` after `parentSpan.finish()` has been called. If we keep with the philosophy that a "context" and Span are the same object, then I want to question why that sequence of calls in invalid in the first place? I realize that it's what the OT Spec says, but the actual motivation for that spec was that you cannot call methods on the span that cause _additional reporting_, such as tagging, logs, events, but calling other methods should be allowed. Maybe we should clarify that.

As for the basictracer actually panicing in this case, isn't it simply because it stores the "context" inside the raw span, a pooled/reusable object? If instead it stored both baggage and "context" in the Span itself, then children could be created on a `finish`-ed Span just fine.

**Comment by yurishkuro** [comment]
PS: our internal tracer implementations do not use the "raw span" approach, just a single Span object, and as a result have no issues if children are created after the parent is finished.

**Comment by bg451** [comment]
> I realize that it's what the OT Spec says, but the actual motivation for that spec was that you cannot call methods on the span that cause additional reporting, such as tagging, logs, events, but calling other methods should be allowed. Maybe we should clarify that.

+1, it isn't too clear if creating a span from a finished parent actually counts as an operation on the parent span.

> isn't it simply because it stores the "context" inside the raw span, a pooled/reusable object? If instead it stored both baggage and "context" in the Span itself, then children could be created on a finish-ed Span just fine.

That wouldn't really fix the problem, since the span implementation `spanImpl` is recycling itself after finish. `RawSpan`, which is inside `spanImpl`, never gets recycled, but instead gets replaced when a`spanImpl` is taken out of the pool. You'd have to stop recycling the Span once finish() has been called.

**Comment by bg451** [comment]
I went ahead and opened up a PR for the inject/extract way of fixing this to get an idea of what it would look like. Check out github.com/opentracing/basictracer-go/pull/25

**Comment by bensigelman** [comment]
@yurishkuro said:

> The primary use case here is parentSpan.startChildSpan() after parentSpan.finish() has been called. If we keep with the philosophy that a "context" and Span are the same object, then I want to question why that sequence of calls in invalid in the first place? I realize that it's what the OT Spec says, but the actual motivation for that spec was that you cannot call methods on the span that cause additional reporting, such as tagging, logs, events, but calling other methods should be allowed. Maybe we should clarify that.

FWIW, creating a child span *could* have reporting implications for some parent impls. E.g., it would be a way for a parent span to have a lower bound on the number of children spans that are *expected*, and thus do integrity checks after assembly. (I've even talked about doing that at times :)

I agree that the explicit `TraceContext` of yesteryear would make this issue go away trivially.

**Comment by bg451** [comment]
Going to close this now that the span pool is disabled by default.
